In [1]:
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

/home/rodrigo/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
X_train = pd.read_csv('X_train.csv', index_col=0)
y_train = pd.read_csv('y_train.csv', index_col=0)

X_test = pd.read_csv('X_test.csv', index_col=0)
y_test = pd.read_csv('y_test.csv', index_col=0)

In [3]:
X_train

,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10,...,Column26,Column27,Column28,Column29,Column30,Column31,Column32,Column33,Column34,Column35
0,101,11722,5138,1105,1208,2393,15719,1161,1250,1106,...,0,0,0,0,0,0,0,0,0,0
1,101,4388,1121,15973,119,2270,7911,170,1248,1105,...,1103,3227,13670,12549,5753,106,106,102,0,0
2,101,3278,1105,1149,1293,11215,102,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,101,17321,3625,119,102,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,101,197,197,157,197,197,2959,119,115,13881,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,101,17037,1742,112,188,4809,106,11896,1361,4179,...,170,14147,119,1109,1611,2087,7535,4268,1494,102
99996,101,1110,9254,1272,7685,1575,1222,23973,1105,9632,...,15969,155,21678,17020,13821,24805,14731,1592,11607,102
99997,101,197,197,157,197,197,1138,1128,1151,6612,...,150,25290,12809,4759,8413,131,120,120,4296,102
99998,101,1422,2549,1110,1166,1171,1106,1103,1107,24215,...,0,0,0,0,0,0,0,0,0,0
99999,101,178,1198,16118,1174,1139,3919,1335,1240,6020,...,1181,4616,5871,2328,2328,2328,2328,2328,13280,102

In [4]:
scaler = StandardScaler()

scaler.fit(X_train)

StandardScaler()

In [5]:
X_train_scaled = pd.DataFrame(scaler.transform(X_train))
X_test_scaled = pd.DataFrame(scaler.transform(X_test))

In [6]:
X_train_scaled

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,0.0,1.656889,0.651405,-0.182178,-0.179580,0.101742,2.059803,-0.394029,-0.327963,-0.346626,...,-0.351713,-0.342855,-0.328419,-0.316885,-0.304277,-0.291979,-0.276669,-0.266609,-0.253662,-0.541303
1,0.0,0.290910,-0.236004,3.432645,-0.437292,0.072779,0.714062,-0.585122,-0.328361,-0.346830,...,-0.053832,0.550889,3.629731,3.419687,1.444357,-0.259156,-0.242106,-0.232466,-0.253662,-0.541303
2,0.0,0.084169,-0.239538,-0.171481,-0.159465,2.179056,-0.631851,-0.617902,-0.577065,-0.572269,...,-0.351713,-0.342855,-0.328419,-0.316885,-0.304277,-0.291979,-0.276669,-0.266609,-0.253662,-0.541303
3,0.0,2.699720,0.317163,-0.421902,-0.441315,-0.461737,-0.649431,-0.617902,-0.577065,-0.572269,...,-0.351713,-0.342855,-0.328419,-0.316885,-0.304277,-0.291979,-0.276669,-0.266609,-0.253662,-0.541303
4,0.0,-0.489677,-0.440128,-0.412664,-0.418833,-0.415350,-0.139435,-0.594956,-0.554148,2.259684,...,-0.351713,-0.342855,-0.328419,-0.316885,-0.304277,-0.291979,-0.276669,-0.266609,-0.253662,-0.541303
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,0.0,2.646824,-0.098817,-0.423604,-0.420963,0.670637,-0.631162,1.675982,-0.305843,0.280316,...,-0.305802,3.575271,-0.293963,0.013330,0.185389,0.354247,2.180192,1.162007,0.271363,1.847395
99996,0.0,-0.319628,1.560685,-0.141576,1.353201,-0.090872,-0.438814,4.004768,-0.356859,1.392818,...,3.960948,-0.299927,5.948449,4.750965,3.896640,7.388726,4.526518,0.266277,3.825295,1.847395
99997,0.0,-0.489677,-0.440128,-0.412664,-0.418833,-0.415350,-0.453292,-0.400392,-0.347692,0.776689,...,-0.311203,6.661415,3.380429,1.100148,2.252869,-0.251415,-0.237542,-0.226441,1.256047,1.847395
99998,0.0,-0.261517,0.079461,-0.180963,-0.189519,-0.186002,-0.458808,-0.405213,-0.356460,4.367991,...,-0.351713,-0.342855,-0.328419,-0.316885,-0.304277,-0.291979,-0.276669,-0.266609,-0.253662,-0.541303
99999,0.0,-0.493215,-0.218993,3.467899,-0.187626,-0.193537,0.026025,-0.360477,-0.329956,0.655911,...,-0.032767,0.935584,1.371530,0.376297,0.403323,0.428871,0.482398,0.512636,4.413224,1.847395

In [12]:
print("starting")

param_grid = {'C': np.logspace(-1, 3, 5), 'kernel': ['rbf', 'poly'], 'gamma': ['scale', 'auto']}

svm = SVC()

grid_search = GridSearchCV(svm, param_grid, cv=5, verbose=2, n_jobs=-1)
grid_search.fit(X_train_scaled, y_train)

starting

In [11]:
grid_search.best_params_

{'C': 10, 'kernel': 'rbf', 'gamma': 'scale'}

In [10]:
grid_search.best_score_

0.640132

In [14]:
accuracy = grid_search.score(X_test_scaled, y_test)
print(f"Accuracy on the test set: {accuracy:.2f}")

Accuracy on the test set: 0.61